// GitHub topics arrive as lowercase slugs ("campus-placements", "byok").
// Render them as readable labels while keeping known acronyms uppercase.
const ACRONYMS = new Set([
	"ai",
	"ml",
	"nlp",
	"llm",
	"api",
	"rest",
	"graphql",
	"sdk",
	"cli",
	"gui",
	"ui",
	"ux",
	"css",
	"html",
	"json",
	"yaml",
	"http",
	"https",
	"ssh",
	"sql",
	"nosql",
	"db",
	"orm",
	"crud",
	"jwt",
	"oauth",
	"ci",
	"cd",
	"cicd",
	"aws",
	"gcp",
	"os",
	"pwa",
	"spa",
	"ssr",
	"ssg",
	"seo",
	"iot",
	"vr",
	"ar",
	"pdf",
	"csv",
	"npm",
	"pip",
	"php",
	"jvm",
	"jiit",
	"osdc",
	"byok",
	"gfg",
	"wifi",
	"qr",
	"otp",
	"2fa",
	"3d",
]);

// Brand casing that neither plain capitalisation nor the acronym list gets right.
const BRANDS: Record<string, string> = {
	javascript: "JavaScript",
	typescript: "TypeScript",
	nodejs: "Node.js",
	node: "Node.js",
	nextjs: "Next.js",
	nuxtjs: "Nuxt",
	reactjs: "React",
	react: "React",
	vuejs: "Vue",
	expressjs: "Express",
	nestjs: "NestJS",
	fastapi: "FastAPI",
	django: "Django",
	flask: "Flask",
	streamlit: "Streamlit",
	tailwindcss: "Tailwind CSS",
	graphql: "GraphQL",
	mongodb: "MongoDB",
	postgresql: "PostgreSQL",
	postgres: "PostgreSQL",
	mysql: "MySQL",
	sqlite: "SQLite",
	redis: "Redis",
	firebase: "Firebase",
	supabase: "Supabase",
	github: "GitHub",
	"github-actions": "GitHub Actions",
	gitlab: "GitLab",
	githubpages: "GitHub Pages",
	leetcode: "LeetCode",
	codechef: "CodeChef",
	codeforces: "Codeforces",
	hackerrank: "HackerRank",
	geeksforgeeks: "GeeksforGeeks",
	openai: "OpenAI",
	chatgpt: "ChatGPT",
	langchain: "LangChain",
	pytorch: "PyTorch",
	tensorflow: "TensorFlow",
	numpy: "NumPy",
	pandas: "pandas",
	opencv: "OpenCV",
	jquery: "jQuery",
	dotnet: ".NET",
	ios: "iOS",
	macos: "macOS",
	android: "Android",
	linux: "Linux",
	docker: "Docker",
	kubernetes: "Kubernetes",
	vercel: "Vercel",
	netlify: "Netlify",
	cloudflare: "Cloudflare",
	telegram: "Telegram",
	whatsapp: "WhatsApp",
	youtube: "YouTube",
	pyodide: "Pyodide",
	astro: "Astro",
	svelte: "Svelte",
	fdroid: "F-Droid",
	"f-droid": "F-Droid",
	webapp: "Web App",
	webdev: "Web Dev",
};

export function formatTopic(topic: string): string {
	const key = topic.trim().toLowerCase();
	if (BRANDS[key]) return BRANDS[key];

	return key
		.split(/[-_\s]+/)
		.filter(Boolean)
		.map((word) => {
			if (BRANDS[word]) return BRANDS[word];
			if (ACRONYMS.has(word)) return word.toUpperCase();
			return word.charAt(0).toUpperCase() + word.slice(1);
		})
		.join(" ");
}
