/* Generated by scripts/sync-markdown.mjs from packages/markdown/directives.ts.
 * Edit the canonical copy, then re-run the sync. */
/**
 * Container directives (`:::name`) for markdown-it.
 *
 * This is the extension point that replaces MDX for this content pipeline.
 * Posts travel between the API, two sites, and the editor as plain Markdown
 * strings, so a construct that needs a component scope to resolve against —
 * which is what `<TwoCol>` in MDX needs — can never be evaluated on the
 * consuming side. A container directive is ordinary block Markdown: the body is
 * handed back to the normal block tokenizer, so every existing renderer rule
 * (headings, fences, mermaid, callouts, task lists) applies inside a column
 * with no extra work.
 *
 *     ::::two-col{ratio="2:1"}
 *     :::col
 *     left
 *     :::
 *     :::col
 *     right
 *     :::
 *     ::::
 *
 * Written here rather than pulled from `markdown-it-container` for two reasons:
 * the nesting rules below have to be exact (a column directive sits inside a
 * grid directive), and the module is vendored into three build roots, so every
 * avoided dependency is one less thing to keep in step.
 */

export const COLUMN_RATIOS = {
  '1:1': '1fr 1fr',
  '2:1': '2fr 1fr',
  '1:2': '1fr 2fr',
} as const

export type ColumnRatio = keyof typeof COLUMN_RATIOS

export const CALLOUT_NAMES = [
  'note',
  'tip',
  'important',
  'warning',
  'caution',
  'danger',
] as const

export type CalloutName = (typeof CALLOUT_NAMES)[number]

export const DIRECTIVE_NAMES = ['two-col', 'col', ...CALLOUT_NAMES] as const

export type DirectiveName = (typeof DIRECTIVE_NAMES)[number]

const DIRECTIVE_NAME_SET: ReadonlySet<string> = new Set(DIRECTIVE_NAMES)

export function isCalloutName(name: string): name is CalloutName {
  return (CALLOUT_NAMES as readonly string[]).includes(name)
}

export type DirectiveInfo = {
  name: DirectiveName
  /** Parsed `{key="value"}` attributes. */
  attrs: Record<string, string>
}

const MARKER = ':'
export const MIN_MARKERS = 3

const INFO_PATTERN = /^([a-z][a-z0-9-]*)\s*([\s\S]*)$/i
const ATTR_PATTERN =
  /([a-z][a-z0-9-]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s}'"]+))/gi

/**
 * The attribute a bare value maps to, so `:::note Heads up` and
 * `::::two-col 2:1` work without anyone having to remember `{key="…"}`.
 */
const POSITIONAL_ATTR: Partial<Record<DirectiveName, string>> = {
  'two-col': 'ratio',
  note: 'title',
  tip: 'title',
  important: 'title',
  warning: 'title',
  caution: 'title',
  danger: 'title',
}

/**
 * Parse the text after the opening colons.
 *
 * Returns `null` for anything that is not a known directive, which leaves the
 * line to be parsed as ordinary Markdown rather than silently swallowed.
 */
export function parseDirectiveInfo(info: string): DirectiveInfo | null {
  const match = INFO_PATTERN.exec(info.trim())
  if (!match) return null

  const name = match[1].toLowerCase()
  if (!DIRECTIVE_NAME_SET.has(name)) return null
  const directiveName = name as DirectiveName

  const rest = match[2].trim()
  if (!rest) return { name: directiveName, attrs: {} }

  if (rest.startsWith('{')) {
    if (!rest.endsWith('}')) return null
    const attrs: Record<string, string> = {}
    const body = rest.slice(1, -1)
    for (const attr of body.matchAll(ATTR_PATTERN)) {
      attrs[attr[1].toLowerCase()] = attr[2] ?? attr[3] ?? attr[4] ?? ''
    }
    return { name: directiveName, attrs }
  }

  const positional = POSITIONAL_ATTR[directiveName]
  if (!positional) return null
  return { name: directiveName, attrs: { [positional]: rest } }
}

/** Number of leading colons on a line, ignoring indentation. */
export function leadingMarkers(line: string): number {
  const trimmed = line.trimStart()
  let count = 0
  while (count < trimmed.length && trimmed[count] === MARKER) count++
  return count
}

/** A code fence opener/closer, so directive scanning can skip a fenced body. */
export function codeFenceMarker(line: string): string | null {
  const match = /^(`{3,}|~{3,})/.exec(line.trim())
  return match ? match[1][0] : null
}

/**
 * Locate the fence that closes the directive opened on `openLine`.
 *
 * Returns `-1` when the directive is never closed, which the caller treats as
 * running to the end of the block — the same forgiving behaviour markdown-it
 * gives an unterminated code fence.
 */
function findClosingFence(
  lines: readonly string[],
  openLine: number,
  markerCount: number,
  endLine: number,
): number {
  let depth = 1
  let codeMarker: string | null = null

  for (let index = openLine + 1; index < endLine; index++) {
    const line = lines[index]

    // A fenced code block may legitimately contain `:::`, so its body is
    // skipped rather than scanned for fences.
    const fence = codeFenceMarker(line)
    if (fence) {
      if (codeMarker === null) codeMarker = fence
      else if (codeMarker === fence) codeMarker = null
      continue
    }
    if (codeMarker !== null) continue

    const run = leadingMarkers(line)
    // A shorter run belongs to a nested directive and cannot close this one,
    // which is what lets `::::two-col` wrap `:::col` unambiguously.
    if (run < MIN_MARKERS || run < markerCount) continue

    const rest = line.trimStart().slice(run).trim()
    if (rest === '') {
      depth--
      if (depth === 0) return index
      continue
    }
    // An equal-length opener nests, so `:::two-col` can also wrap `:::col`.
    if (parseDirectiveInfo(rest)) depth++
  }

  return -1
}

/**
 * markdown-it block rule. Emits `directive_open` / `directive_close` tokens
 * carrying the parsed info on `meta`, and tokenizes the body as normal
 * Markdown in between.
 */
function directiveRule(
  state: any,
  startLine: number,
  endLine: number,
  silent: boolean,
): boolean {
  // Four spaces of indent means an indented code block, not a directive.
  if (state.sCount[startLine] - state.blkIndent >= 4) return false

  const start = state.bMarks[startLine] + state.tShift[startLine]
  const max = state.eMarks[startLine]
  if (state.src[start] !== MARKER) return false

  let pos = start
  while (pos < max && state.src[pos] === MARKER) pos++
  const markerCount = pos - start
  if (markerCount < MIN_MARKERS) return false

  const info = state.src.slice(pos, max)
  const directive = parseDirectiveInfo(info)
  if (!directive) return false

  // `silent` means the caller is only probing whether the line terminates a
  // paragraph, so no tokens may be produced.
  if (silent) return true

  const lines: string[] = []
  for (let index = startLine; index < endLine; index++) {
    lines.push(
      state.src.slice(
        state.bMarks[index] + state.tShift[index],
        state.eMarks[index],
      ),
    )
  }
  // `findClosingFence` indexes the slice, so shift back into document lines.
  const relativeClose = findClosingFence(
    lines,
    0,
    markerCount,
    endLine - startLine,
  )
  const closeLine = relativeClose === -1 ? -1 : startLine + relativeClose
  const bodyEnd = closeLine === -1 ? endLine : closeLine

  const oldParentType = state.parentType
  const oldLineMax = state.lineMax
  state.parentType = 'directive'
  state.lineMax = bodyEnd

  const markup = MARKER.repeat(markerCount)

  const open = state.push('directive_open', 'div', 1)
  open.markup = markup
  open.block = true
  open.info = info.trim()
  open.meta = directive
  open.map = [startLine, bodyEnd]

  state.line = startLine + 1
  state.md.block.tokenize(state, state.line, bodyEnd)

  const close = state.push('directive_close', 'div', -1)
  close.markup = markup
  close.block = true
  close.meta = directive

  state.parentType = oldParentType
  state.lineMax = oldLineMax
  state.line = closeLine === -1 ? endLine : closeLine + 1
  return true
}

export function directivesPlugin(md: any): void {
  md.block.ruler.before('fence', 'directive', directiveRule, {
    alt: ['paragraph', 'reference', 'blockquote', 'list'],
  })
}
