/* Generated by scripts/sync-markdown.mjs from packages/markdown/index.ts.
 * Edit the canonical copy, then re-run the sync. */
export {
  CALLOUT_NAMES,
  COLUMN_RATIOS,
  COMPONENT_NAMES,
  COMPONENTS,
  type AttrSpec,
  type AttrValues,
  type CalloutName,
  type ColumnRatio,
  type ComponentSpec,
  escapeHtml,
  findByDirective,
  findByTag,
  getIcon,
  type HeadingEntry,
  ICON_NAMES,
  isCalloutName,
  isIconName,
  type RenderCtx,
  resolveAttrs,
} from './components'
export {
  DIRECTIVE_NAMES,
  type DirectiveInfo,
  parseDirectiveInfo,
} from './directives'
export { parseOpenTag, type ParsedTag } from './jsx'
export {
  countWords,
  type DocumentOutline,
  extractOutline,
  RENDERER_VERSION,
  usedComponents,
} from './outline'
export {
  extractHeadings,
  parseExplicitHeadingId,
  renderMarkdown,
  slugifyHeading,
  type RenderOptions,
  type ResolvedImage,
} from './render'
export { EMPTY_THEME, type MarkdownTheme } from './theme'
export {
  convertRelativeUrl,
  type RootRelativeMode,
  type UrlOptions,
} from './urls'
export {
  formatDirectiveIssues,
  validateDirectives,
  validateDocument,
  type DirectiveIssue,
} from './validate'
