/* Generated by scripts/sync-markdown.mjs from packages/markdown/index.ts.
 * Edit the canonical copy, then re-run the sync. */
export {
  CALLOUT_NAMES,
  COLUMN_RATIOS,
  DIRECTIVE_NAMES,
  type CalloutName,
  type ColumnRatio,
  type DirectiveInfo,
  type DirectiveName,
  isCalloutName,
  parseDirectiveInfo,
} from './directives'
export {
  extractHeadings,
  parseExplicitHeadingId,
  renderMarkdown,
  slugifyHeading,
  type RenderOptions,
  type ResolvedImage,
} from './render'
export { EMPTY_THEME, type MarkdownTheme } from './theme'
export {
  convertRelativeUrl,
  type RootRelativeMode,
  type UrlOptions,
} from './urls'
export {
  formatDirectiveIssues,
  validateDirectives,
  type DirectiveIssue,
} from './validate'
