/* Generated by scripts/sync-markdown.mjs from packages/markdown/outline.ts.
 * Edit the canonical copy, then re-run the sync. */
/**
 * Document metadata: headings, components used, and reading stats.
 *
 * This is what the API ships alongside the Markdown so a consumer can build a
 * table of contents before paint, and can tell whether it understands a post
 * before it tries to render it. It is metadata only — the Markdown remains the
 * source of truth, and nothing here is required to display a post.
 *
 * `RENDERER_VERSION` is the contract. Bump it whenever the component vocabulary
 * changes in a way an out-of-date mirror could not render, and a consumer whose
 * vendored copy is older can warn instead of quietly printing `<Steps>` into
 * the page. `server/services/outline.py` asserts the same constant, so a
 * version bump cannot ship to only one half of the pipeline.
 */

import { CALLOUT_NAMES, COMPONENTS, type HeadingEntry } from './components'
import { extractHeadings } from './render'

export const RENDERER_VERSION = 'md-3'

/** Words per minute, matching what tashif.codes already assumes. */
const WORDS_PER_MINUTE = 200

export type DocumentOutline = {
  renderer: string
  headings: HeadingEntry[]
  /** Distinct component names used, in registry order. */
  components: string[]
  wordCount: number
  readingTimeMinutes: number
}

/** Strip the frontmatter block, which is metadata rather than prose. */
function stripFrontmatter(source: string): string {
  if (!source.startsWith('---')) return source
  const end = source.indexOf('\n---', 3)
  return end === -1 ? source : source.slice(end + 4)
}

/**
 * Prose word count.
 *
 * Fenced code, component tags, and directive fences are removed first: a post
 * whose bulk is a config listing should not read as a thirty-minute article.
 */
export function countWords(source: string): number {
  const prose = stripFrontmatter(source)
    .replace(/^```[\s\S]*?^```/gm, ' ')
    .replace(/^~~~[\s\S]*?^~~~/gm, ' ')
    .replace(/`[^`\n]*`/g, ' ')
    .replace(/^\s*:{3,}.*$/gm, ' ')
    .replace(/<\/?[A-Za-z][A-Za-z0-9]*(?:\s[^>]*)?\/?>/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')

  const words = prose.match(/[A-Za-z0-9À-ɏ]+(?:['’][A-Za-z]+)?/g)
  return words ? words.length : 0
}

/**
 * Which registered components does this source use?
 *
 * A string scan rather than a parse. A component named inside fenced code is a
 * false positive, which costs a consumer nothing — the list is advisory, used
 * to decide whether to warn about a stale renderer, never to gate rendering.
 */
export function usedComponents(source: string): string[] {
  const body = stripFrontmatter(source)
  const found: string[] = []

  for (const spec of COMPONENTS) {
    const tag = new RegExp(`<${spec.name}(?=[\\s/>])`, 'i')
    const directives = [spec.directive, ...(spec.aliases ?? [])]
    const directive = new RegExp(`^\\s*:{3,}(?:${directives.join('|')})\\b`, 'mi')

    // A callout also has the GitHub alert spelling, which `callouts.ts` rewrites
    // into the same tokens. A post using only that form still uses the
    // component, so it has to count here too.
    const alert = (CALLOUT_NAMES as readonly string[]).includes(spec.directive)
      ? new RegExp(`^\\s*>\\s*\\[!${spec.directive}\\]`, 'mi')
      : null

    if (tag.test(body) || directive.test(body) || alert?.test(body)) {
      found.push(spec.name)
    }
  }

  return found
}

/** Everything the API needs to describe a post without rendering it. */
export function extractOutline(source: string): DocumentOutline {
  const wordCount = countWords(source)
  return {
    renderer: RENDERER_VERSION,
    headings: extractHeadings(stripFrontmatter(source)),
    components: usedComponents(source),
    wordCount,
    readingTimeMinutes: Math.max(1, Math.round(wordCount / WORDS_PER_MINUTE)),
  }
}
