/* Generated by scripts/sync-markdown.mjs from packages/markdown/tasklists.ts.
 * Edit the canonical copy, then re-run the sync. */
/**
 * GFM task lists (`- [ ] todo`).
 *
 * Implemented here rather than via `markdown-it-task-lists` so the vendored
 * module stays dependency-free apart from markdown-it itself — the plugin also
 * ships no types, which would mean maintaining the same hand-written
 * declaration file in all three build roots.
 */

const TASK_MARKER = /^\[([ xX])\][  ]/

function isTaskItem(tokens: any[], index: number): boolean {
  return (
    index >= 2 &&
    tokens[index].type === 'inline' &&
    tokens[index - 1].type === 'paragraph_open' &&
    tokens[index - 2].type === 'list_item_open' &&
    TASK_MARKER.test(tokens[index].content)
  )
}

/** The `bullet_list_open` / `ordered_list_open` that owns this item. */
function findParentList(tokens: any[], index: number): any | null {
  for (let position = index - 2; position >= 0; position--) {
    const type = tokens[position].type
    if (type === 'bullet_list_open' || type === 'ordered_list_open') {
      return tokens[position]
    }
  }
  return null
}

export function taskListsPlugin(md: any): void {
  md.core.ruler.after('inline', 'task_lists', (state: any) => {
    const tokens: any[] = state.tokens

    for (let index = 2; index < tokens.length; index++) {
      if (!isTaskItem(tokens, index)) continue

      const inline = tokens[index]
      const checked = /^\[[xX]\]/.test(inline.content)

      inline.content = inline.content.replace(TASK_MARKER, '')
      const firstChild = inline.children?.[0]
      if (firstChild) {
        firstChild.content = firstChild.content.replace(TASK_MARKER, '')
      }

      const checkbox = new state.Token('html_inline', '', 0)
      checkbox.content = `<input class="md-task-checkbox" type="checkbox" disabled${
        checked ? ' checked' : ''
      }> `
      inline.children?.unshift(checkbox)

      tokens[index - 2].attrJoin('class', 'md-task-item')
      findParentList(tokens, index)?.attrJoin('class', 'md-task-list')
    }

    return true
  })
}
