/* Generated by scripts/sync-markdown.mjs from packages/markdown/urls.ts.
 * Edit the canonical copy, then re-run the sync. */
/**
 * URL rewriting for Markdown that was authored somewhere other than where it is
 * rendered.
 *
 * Two different kinds of content flow through the renderer and they disagree
 * about what a root-relative `/foo` means:
 *
 *  - Blog posts: `/images/blog/…` is a real path on the site that serves the
 *    post, so it must be left alone (or pointed at that site's origin when a
 *    different site is rendering the same Markdown).
 *  - GitHub READMEs and generated docs: `/foo` is repository-root-relative and
 *    has to become a raw.githubusercontent URL to resolve at all.
 *
 * Getting this backwards is how root-relative blog images ended up rewritten to
 * raw GitHub paths that do not exist, so the behaviour is an explicit option
 * rather than something inferred from the URL.
 */

import { FILE_ICON, FOLDER_ICON } from './icons'
import { cx, type MarkdownTheme } from './theme'

export type RootRelativeMode = 'site' | 'repo'

export type UrlOptions = {
  /** Repository the Markdown lives in, e.g. `https://github.com/user/repo`. */
  githubBaseUrl?: string
  /** Docs project slug, used to serve bundled `images/…` from the site. */
  project?: string
  rootRelative?: RootRelativeMode
  /**
   * Origin to prefix onto root-relative URLs. Set this when one site renders
   * Markdown whose assets are hosted by another.
   */
  assetBaseUrl?: string
}

const HAS_SCHEME = /^[a-z][a-z0-9+.-]*:/i

/** Repository URL to the raw-content host, so images resolve to bytes. */
function rawBase(githubBaseUrl: string): string {
  if (
    githubBaseUrl.includes('github.com') &&
    !githubBaseUrl.includes('raw.githubusercontent.com')
  ) {
    // `HEAD` rather than a branch name: the same helper serves repositories
    // whose default branch is not `main`.
    return `${githubBaseUrl.replace('github.com', 'raw.githubusercontent.com')}/HEAD`
  }
  return githubBaseUrl
}

function withAssetBase(url: string, assetBaseUrl?: string): string {
  if (!assetBaseUrl) return url
  return `${assetBaseUrl.replace(/\/+$/, '')}${url}`
}

export function convertRelativeUrl(url: string, options: UrlOptions): string {
  if (!url) return url
  if (url.startsWith('#')) return url
  if (url.startsWith('//')) return url

  const { githubBaseUrl, project, rootRelative = 'site', assetBaseUrl } = options

  // Root-relative handling comes first: it is the one case that applies even
  // without a repository URL, and the `repo` reading must not leak into posts.
  if (url.startsWith('/')) {
    if (rootRelative === 'repo' && githubBaseUrl) {
      return rawBase(githubBaseUrl) + url
    }
    return withAssetBase(url, assetBaseUrl)
  }

  // `file://` links are emitted by the docs generator and point into the repo.
  if (url.startsWith('file://')) {
    if (!githubBaseUrl) return url
    return `${githubBaseUrl}/blob/HEAD/${url.slice('file://'.length)}`
  }

  if (HAS_SCHEME.test(url)) return url
  if (!githubBaseUrl) return url

  // Docs images are copied into the site rather than fetched from GitHub.
  if (project && (url.startsWith('images/') || url.startsWith('./images/'))) {
    return `/docs-assets/${project}/${url.replace(/^\.\//, '')}`
  }

  const base = rawBase(githubBaseUrl)
  if (url.startsWith('./')) return `${base}/${url.slice(2)}`
  if (url.startsWith('../')) return `${base}/${url.replace(/^\.\.\//, '')}`
  return `${base}/${url}`
}

export function convertSrcset(srcset: string, options: UrlOptions): string {
  return srcset
    .split(',')
    .map((entry) => {
      const trimmed = entry.trim()
      if (!trimmed) return trimmed

      const parts = trimmed.split(/\s+/)
      const src = parts.shift() || ''
      const descriptor = parts.join(' ')
      const converted = convertRelativeUrl(src, options)
      return descriptor ? `${converted} ${descriptor}` : converted
    })
    .join(', ')
}

/** Rewrite one attribute on a raw HTML tag, preserving its quoting style. */
function updateTagAttribute(
  tag: string,
  attribute: string,
  transform: (value: string) => string,
): string {
  const pattern = new RegExp(
    `\\b${attribute}\\s*=\\s*("([^"]*)"|'([^']*)'|([^\\s>]+))`,
    'i',
  )

  return tag.replace(
    pattern,
    (_match, _raw, doubleQuoted, singleQuoted, bare) => {
      const value = doubleQuoted ?? singleQuoted ?? bare ?? ''
      const converted = transform(value)
      if (doubleQuoted !== undefined) return `${attribute}="${converted}"`
      if (singleQuoted !== undefined) return `${attribute}='${converted}'`
      return `${attribute}=${converted}`
    },
  )
}

/**
 * Rewrite raw-HTML media that markdown-it passed through untouched, and turn
 * `<cite>` file lists from the docs generator into reference cards.
 *
 * Runs on the rendered string because these tags never become Markdown tokens —
 * they arrive as `html_block` content.
 */
export function postProcessHtml(
  html: string,
  options: UrlOptions,
  theme: MarkdownTheme = {},
): string {
  const { githubBaseUrl } = options
  const convert = (url: string) => convertRelativeUrl(url, options)

  let output = html

  output = output.replace(/<img\b[^>]*>/gi, (tag) => {
    let updated = updateTagAttribute(tag, 'src', convert)
    updated = updateTagAttribute(updated, 'srcset', (value) =>
      convertSrcset(value, options),
    )
    return updateTagAttribute(updated, 'data-src', convert)
  })

  output = output.replace(
    /<source\b[^>]*\bsrcset=(["'])([^"']+)\1[^>]*>/gi,
    (tag) => updateTagAttribute(tag, 'srcset', (value) => convertSrcset(value, options)),
  )

  output = output.replace(/<video\b[^>]*>/gi, (tag) => {
    const updated = updateTagAttribute(tag, 'src', convert)
    return updateTagAttribute(updated, 'poster', convert)
  })

  output = output.replace(/<audio\b[^>]*>/gi, (tag) =>
    updateTagAttribute(tag, 'src', convert),
  )

  output = output.replace(/<a\b[^>]*>/gi, (tag) =>
    updateTagAttribute(tag, 'href', convert),
  )

  if (!githubBaseUrl) return output

  output = output.replace(/<cite>([\s\S]*?)<\/cite>/g, (_match, inner: string) => {
    const links: string[] = []
    for (const link of inner.matchAll(/\[([^\]]+)\]\(file:\/\/([^)]+)\)/g)) {
      const [, label, filePath] = link
      links.push(
        `<a href="${githubBaseUrl}/blob/HEAD/${filePath}" target="_blank" rel="noopener noreferrer" class="${cx('md-cite-link', theme.citeLink)}">${FILE_ICON}<span class="md-cite-label">${label}</span></a>`,
      )
    }
    if (!links.length) return `<cite>${inner}</cite>`

    return `<div class="${cx('md-cite', theme.citeCard)}"><div class="${cx('md-cite-heading', theme.citeHeading)}">${FOLDER_ICON} Referenced Files</div><div class="${cx('md-cite-body', theme.citeBody)}">${links.join('')}</div></div>`
  })

  output = output.replace(
    /href="file:\/\/([^"]+)"/g,
    (_match, filePath: string) =>
      `href="${githubBaseUrl}/blob/HEAD/${filePath}" target="_blank" rel="noopener noreferrer"`,
  )

  return output
}

/**
 * Convert `[label](file://path)` before parsing.
 *
 * markdown-it does not treat `file:` as a linkifiable scheme, so these are left
 * as literal text unless they are rewritten up front. `<cite>` blocks are held
 * back for `postProcessHtml`, which renders them as cards instead of links.
 */
export function preProcessFileLinks(
  content: string,
  githubBaseUrl?: string,
): string {
  if (!githubBaseUrl || !content) return content

  return content.replace(
    /(<cite>[\s\S]*?<\/cite>)|(\[([^\]]+)\]\(file:\/\/([^)]+)\))/g,
    (match, citeBlock, _link, label, filePath) => {
      if (citeBlock) return citeBlock
      return `[${label}](${githubBaseUrl}/blob/HEAD/${filePath})`
    },
  )
}
