import os
import re


def fix_content(content):
    # 1. Remove AI Source Citations
    # Matches "Sources:" or "**Sources**:" until end of line, case insensitive
    content = re.sub(
        r"^(?:\*\*Sources\*\*|Sources):.*$",
        "",
        content,
        flags=re.MULTILINE | re.IGNORECASE,
    )

    # 2. Remove "Relevant source files" sections
    # Matches "Relevant source files" followed by a list of markdown links
    content = re.sub(
        r"^Relevant source files.*(?:\n\* \[[^\]]+\]\([^\)]+\))*",
        "",
        content,
        flags=re.MULTILINE | re.IGNORECASE,
    )

    # 3. Fix double/triple code fences
    # Replace ``` followed by another ``` (with optional lang) on next lines
    content = re.sub(r"```\s*\n```(\w*)\n", r"```\1\n", content)
    content = re.sub(r"\n```\s*\n```$", r"\n```", content, flags=re.MULTILINE)

    # 4. Unwrap images and remove orphan fences near images
    # Remove backticks that are immediately before or after an image tag
    content = re.sub(r"```\s*\n(!\[.*?\]\(.*?\))", r"\1", content)
    content = re.sub(r"(!\[.*?\]\(.*?\))\n\s*```", r"\1", content)

    # 5. Fix internal links: [Label](/org/repo/filename) -> [Label](filename)
    # This specifically targets the absolute-looking links generated by the docs tool
    content = re.sub(r"\[([^\]]+)\]\(/[^/]+/[^/]+/([^)]+)\)", r"[\1](\2)", content)

    # 6. Final cleanup of extra whitespace/newlines
    content = re.sub(r"\n{3,}", "\n\n", content)

    return content.strip() + "\n"


def process_docs(docs_dir):
    for root, dirs, files in os.walk(docs_dir):
        for file in files:
            if file.endswith(".md"):
                file_path = os.path.join(root, file)
                print(f"Processing {file_path}...")

                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()

                fixed_content = fix_content(content)

                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(fixed_content)


if __name__ == "__main__":
    DOCS_DIR = os.path.join(os.getcwd(), "src/data/docs")
    process_docs(DOCS_DIR)
