"""
Utility functions for the analytics API
"""


COUNTRY_MAP = {
    "af": {"flag": "🇦🇫", "name": "Afghanistan"},
    "ax": {"flag": "🇦🇽", "name": "Åland Islands"},
    "al": {"flag": "🇦🇱", "name": "Albania"},
    "dz": {"flag": "🇩🇿", "name": "Algeria"},
    "as": {"flag": "🇦🇸", "name": "American Samoa"},
    "ad": {"flag": "🇦🇩", "name": "Andorra"},
    "ao": {"flag": "🇦🇴", "name": "Angola"},
    "ai": {"flag": "🇦🇮", "name": "Anguilla"},
    "aq": {"flag": "🇦🇶", "name": "Antarctica"},
    "ag": {"flag": "🇦🇬", "name": "Antigua and Barbuda"},
    "ar": {"flag": "🇦🇷", "name": "Argentina"},
    "am": {"flag": "🇦🇲", "name": "Armenia"},
    "aw": {"flag": "🇦🇼", "name": "Aruba"},
    "au": {"flag": "🇦🇺", "name": "Australia"},
    "at": {"flag": "🇦🇹", "name": "Austria"},
    "az": {"flag": "🇦🇿", "name": "Azerbaijan"},
    "bs": {"flag": "🇧🇸", "name": "Bahamas"},
    "bh": {"flag": "🇧🇭", "name": "Bahrain"},
    "bd": {"flag": "🇧🇩", "name": "Bangladesh"},
    "bb": {"flag": "🇧🇧", "name": "Barbados"},
    "by": {"flag": "🇧🇾", "name": "Belarus"},
    "be": {"flag": "🇧🇪", "name": "Belgium"},
    "bz": {"flag": "🇧🇿", "name": "Belize"},
    "bj": {"flag": "🇧🇯", "name": "Benin"},
    "bm": {"flag": "🇧🇲", "name": "Bermuda"},
    "bt": {"flag": "🇧🇹", "name": "Bhutan"},
    "bo": {"flag": "🇧🇴", "name": "Bolivia"},
    "bq": {"flag": "🇧🇶", "name": "Bonaire, Sint Eustatius and Saba"},
    "ba": {"flag": "🇧🇦", "name": "Bosnia and Herzegovina"},
    "bw": {"flag": "🇧🇼", "name": "Botswana"},
    "bv": {"flag": "🇧🇻", "name": "Bouvet Island"},
    "br": {"flag": "🇧🇷", "name": "Brazil"},
    "io": {"flag": "🇮🇴", "name": "British Indian Ocean Territory"},
    "bn": {"flag": "🇧🇳", "name": "Brunei Darussalam"},
    "bg": {"flag": "🇧🇬", "name": "Bulgaria"},
    "bf": {"flag": "🇧🇫", "name": "Burkina Faso"},
    "bi": {"flag": "🇧🇮", "name": "Burundi"},
    "cv": {"flag": "🇨🇻", "name": "Cabo Verde"},
    "kh": {"flag": "🇰🇭", "name": "Cambodia"},
    "cm": {"flag": "🇨🇲", "name": "Cameroon"},
    "ca": {"flag": "🇨🇦", "name": "Canada"},
    "ky": {"flag": "🇰🇾", "name": "Cayman Islands"},
    "cf": {"flag": "🇨🇫", "name": "Central African Republic"},
    "td": {"flag": "🇹🇩", "name": "Chad"},
    "cl": {"flag": "🇨🇱", "name": "Chile"},
    "cn": {"flag": "🇨🇳", "name": "China"},
    "cx": {"flag": "🇨🇽", "name": "Christmas Island"},
    "cc": {"flag": "🇨🇨", "name": "Cocos (Keeling) Islands"},
    "co": {"flag": "🇨🇴", "name": "Colombia"},
    "km": {"flag": "🇰🇲", "name": "Comoros"},
    "cg": {"flag": "🇨🇬", "name": "Congo (Republic)"},
    "cd": {"flag": "🇨🇩", "name": "Congo (DRC)"},
    "ck": {"flag": "🇨🇰", "name": "Cook Islands"},
    "cr": {"flag": "🇨🇷", "name": "Costa Rica"},
    "hr": {"flag": "🇭🇷", "name": "Croatia"},
    "cu": {"flag": "🇨🇺", "name": "Cuba"},
    "cw": {"flag": "🇨🇼", "name": "Curaçao"},
    "cy": {"flag": "🇨🇾", "name": "Cyprus"},
    "cz": {"flag": "🇨🇿", "name": "Czech Republic"},
    "ci": {"flag": "🇨🇮", "name": "Côte d'Ivoire"},
    "dk": {"flag": "🇩🇰", "name": "Denmark"},
    "dj": {"flag": "🇩🇯", "name": "Djibouti"},
    "dm": {"flag": "🇩🇲", "name": "Dominica"},
    "do": {"flag": "🇩🇴", "name": "Dominican Republic"},
    "ec": {"flag": "🇪🇨", "name": "Ecuador"},
    "eg": {"flag": "🇪🇬", "name": "Egypt"},
    "sv": {"flag": "🇸🇻", "name": "El Salvador"},
    "gq": {"flag": "🇬🇶", "name": "Equatorial Guinea"},
    "er": {"flag": "🇪🇷", "name": "Eritrea"},
    "ee": {"flag": "🇪🇪", "name": "Estonia"},
    "sz": {"flag": "🇸🇿", "name": "Eswatini"},
    "et": {"flag": "🇪🇹", "name": "Ethiopia"},
    "fk": {"flag": "🇫🇰", "name": "Falkland Islands"},
    "fo": {"flag": "🇫🇴", "name": "Faroe Islands"},
    "fj": {"flag": "🇫🇯", "name": "Fiji"},
    "fi": {"flag": "🇫🇮", "name": "Finland"},
    "fr": {"flag": "🇫🇷", "name": "France"},
    "gf": {"flag": "🇬🇫", "name": "French Guiana"},
    "pf": {"flag": "🇵🇫", "name": "French Polynesia"},
    "tf": {"flag": "🇹🇫", "name": "French Southern Territories"},
    "ga": {"flag": "🇬🇦", "name": "Gabon"},
    "gm": {"flag": "🇬🇲", "name": "Gambia"},
    "ge": {"flag": "🇬🇪", "name": "Georgia"},
    "de": {"flag": "🇩🇪", "name": "Germany"},
    "gh": {"flag": "🇬🇭", "name": "Ghana"},
    "gi": {"flag": "🇬🇮", "name": "Gibraltar"},
    "gr": {"flag": "🇬🇷", "name": "Greece"},
    "gl": {"flag": "🇬🇱", "name": "Greenland"},
    "gd": {"flag": "🇬🇩", "name": "Grenada"},
    "gp": {"flag": "🇬🇵", "name": "Guadeloupe"},
    "gu": {"flag": "🇬🇺", "name": "Guam"},
    "gt": {"flag": "🇬🇹", "name": "Guatemala"},
    "gg": {"flag": "🇬🇬", "name": "Guernsey"},
    "gn": {"flag": "🇬🇳", "name": "Guinea"},
    "gw": {"flag": "🇬🇼", "name": "Guinea-Bissau"},
    "gy": {"flag": "🇬🇾", "name": "Guyana"},
    "ht": {"flag": "🇭🇹", "name": "Haiti"},
    "hm": {"flag": "🇭🇲", "name": "Heard Island and McDonald Islands"},
    "va": {"flag": "🇻🇦", "name": "Holy See"},
    "hn": {"flag": "🇭🇳", "name": "Honduras"},
    "hk": {"flag": "🇭🇰", "name": "Hong Kong"},
    "hu": {"flag": "🇭🇺", "name": "Hungary"},
    "is": {"flag": "🇮🇸", "name": "Iceland"},
    "in": {"flag": "🇮🇳", "name": "India"},
    "id": {"flag": "🇮🇩", "name": "Indonesia"},
    "ir": {"flag": "🇮🇷", "name": "Iran"},
    "iq": {"flag": "🇮🇶", "name": "Iraq"},
    "ie": {"flag": "🇮🇪", "name": "Ireland"},
    "im": {"flag": "🇮🇲", "name": "Isle of Man"},
    "il": {"flag": "🇮🇱", "name": "Israel"},
    "it": {"flag": "🇮🇹", "name": "Italy"},
    "jm": {"flag": "🇯🇲", "name": "Jamaica"},
    "jp": {"flag": "🇯🇵", "name": "Japan"},
    "je": {"flag": "🇯🇪", "name": "Jersey"},
    "jo": {"flag": "🇯🇴", "name": "Jordan"},
    "kz": {"flag": "🇰🇿", "name": "Kazakhstan"},
    "ke": {"flag": "🇰🇪", "name": "Kenya"},
    "ki": {"flag": "🇰🇮", "name": "Kiribati"},
    "kp": {"flag": "🇰🇵", "name": "Korea (North)"},
    "kr": {"flag": "🇰🇷", "name": "Korea (South)"},
    "kw": {"flag": "🇰🇼", "name": "Kuwait"},
    "kg": {"flag": "🇰🇬", "name": "Kyrgyzstan"},
    "la": {"flag": "🇱🇦", "name": "Lao People's Democratic Republic"},
    "lv": {"flag": "🇱🇻", "name": "Latvia"},
    "lb": {"flag": "🇱🇧", "name": "Lebanon"},
    "ls": {"flag": "🇱🇸", "name": "Lesotho"},
    "lr": {"flag": "🇱🇷", "name": "Liberia"},
    "ly": {"flag": "🇱🇾", "name": "Libya"},
    "li": {"flag": "🇱🇮", "name": "Liechtenstein"},
    "lt": {"flag": "🇱🇹", "name": "Lithuania"},
    "lu": {"flag": "🇱🇺", "name": "Luxembourg"},
    "mo": {"flag": "🇲🇴", "name": "Macao"},
    "mg": {"flag": "🇲🇬", "name": "Madagascar"},
    "mw": {"flag": "🇲🇼", "name": "Malawi"},
    "my": {"flag": "🇲🇾", "name": "Malaysia"},
    "mv": {"flag": "🇲🇻", "name": "Maldives"},
    "ml": {"flag": "🇲🇱", "name": "Mali"},
    "mt": {"flag": "🇲🇹", "name": "Malta"},
    "mh": {"flag": "🇲🇭", "name": "Marshall Islands"},
    "mq": {"flag": "🇲🇶", "name": "Martinique"},
    "mr": {"flag": "🇲🇷", "name": "Mauritania"},
    "mu": {"flag": "🇲🇺", "name": "Mauritius"},
    "yt": {"flag": "🇾🇹", "name": "Mayotte"},
    "mx": {"flag": "🇲🇽", "name": "Mexico"},
    "fm": {"flag": "🇫🇲", "name": "Micronesia"},
    "md": {"flag": "🇲🇩", "name": "Moldova"},
    "mc": {"flag": "🇲🇨", "name": "Monaco"},
    "mn": {"flag": "🇲🇳", "name": "Mongolia"},
    "me": {"flag": "🇲🇪", "name": "Montenegro"},
    "ms": {"flag": "🇲🇸", "name": "Montserrat"},
    "ma": {"flag": "🇲🇦", "name": "Morocco"},
    "mz": {"flag": "🇲🇿", "name": "Mozambique"},
    "mm": {"flag": "🇲🇲", "name": "Myanmar"},
    "na": {"flag": "🇳🇦", "name": "Namibia"},
    "nr": {"flag": "🇳🇷", "name": "Nauru"},
    "np": {"flag": "🇳🇵", "name": "Nepal"},
    "nl": {"flag": "🇳🇱", "name": "Netherlands"},
    "nc": {"flag": "🇳🇨", "name": "New Caledonia"},
    "nz": {"flag": "🇳🇿", "name": "New Zealand"},
    "ni": {"flag": "🇳🇮", "name": "Nicaragua"},
    "ne": {"flag": "🇳🇪", "name": "Niger"},
    "ng": {"flag": "🇳🇬", "name": "Nigeria"},
    "nu": {"flag": "🇳🇺", "name": "Niue"},
    "nf": {"flag": "🇳🇫", "name": "Norfolk Island"},
    "mk": {"flag": "🇲🇰", "name": "North Macedonia"},
    "mp": {"flag": "🇲🇵", "name": "Northern Mariana Islands"},
    "no": {"flag": "🇳🇴", "name": "Norway"},
    "om": {"flag": "🇴🇲", "name": "Oman"},
    "pk": {"flag": "🇵🇰", "name": "Pakistan"},
    "pw": {"flag": "🇵🇼", "name": "Palau"},
    "ps": {"flag": "🇵🇸", "name": "Palestine, State of"},
    "pa": {"flag": "🇵🇦", "name": "Panama"},
    "pg": {"flag": "🇵🇬", "name": "Papua New Guinea"},
    "py": {"flag": "🇵🇾", "name": "Paraguay"},
    "pe": {"flag": "🇵🇪", "name": "Peru"},
    "ph": {"flag": "🇵🇭", "name": "Philippines"},
    "pn": {"flag": "🇵🇳", "name": "Pitcairn"},
    "pl": {"flag": "🇵🇱", "name": "Poland"},
    "pt": {"flag": "🇵🇹", "name": "Portugal"},
    "pr": {"flag": "🇵🇷", "name": "Puerto Rico"},
    "qa": {"flag": "🇶🇦", "name": "Qatar"},
    "re": {"flag": "🇷🇪", "name": "Réunion"},
    "ro": {"flag": "🇷🇴", "name": "Romania"},
    "ru": {"flag": "🇷🇺", "name": "Russia"},
    "rw": {"flag": "🇷🇼", "name": "Rwanda"},
    "bl": {"flag": "🇧🇱", "name": "Saint Barthélemy"},
    "sh": {"flag": "🇸🇭", "name": "Saint Helena, Ascension and Tristan da Cunha"},
    "kn": {"flag": "🇰🇳", "name": "Saint Kitts and Nevis"},
    "lc": {"flag": "🇱🇨", "name": "Saint Lucia"},
    "mf": {"flag": "🇲🇫", "name": "Saint Martin (French part)"},
    "pm": {"flag": "🇵🇲", "name": "Saint Pierre and Miquelon"},
    "vc": {"flag": "🇻🇨", "name": "Saint Vincent and the Grenadines"},
    "ws": {"flag": "🇼🇸", "name": "Samoa"},
    "sm": {"flag": "🇸🇲", "name": "San Marino"},
    "st": {"flag": "🇸🇹", "name": "Sao Tome and Principe"},
    "sa": {"flag": "🇸🇦", "name": "Saudi Arabia"},
    "sn": {"flag": "🇸🇳", "name": "Senegal"},
    "rs": {"flag": "🇷🇸", "name": "Serbia"},
    "sc": {"flag": "🇸🇨", "name": "Seychelles"},
    "sl": {"flag": "🇸🇱", "name": "Sierra Leone"},
    "sg": {"flag": "🇸🇬", "name": "Singapore"},
    "sx": {"flag": "🇸🇽", "name": "Sint Maarten (Dutch part)"},
    "sk": {"flag": "🇸🇰", "name": "Slovakia"},
    "si": {"flag": "🇸🇮", "name": "Slovenia"},
    "sb": {"flag": "🇸🇧", "name": "Solomon Islands"},
    "so": {"flag": "🇸🇴", "name": "Somalia"},
    "za": {"flag": "🇿🇦", "name": "South Africa"},
    "gs": {"flag": "🇬🇸", "name": "South Georgia and the South Sandwich Islands"},
    "ss": {"flag": "🇸🇸", "name": "South Sudan"},
    "es": {"flag": "🇪🇸", "name": "Spain"},
    "lk": {"flag": "🇱🇰", "name": "Sri Lanka"},
    "sd": {"flag": "🇸🇩", "name": "Sudan"},
    "sr": {"flag": "🇸🇷", "name": "Suriname"},
    "sj": {"flag": "🇸🇯", "name": "Svalbard and Jan Mayen"},
    "se": {"flag": "🇸🇪", "name": "Sweden"},
    "ch": {"flag": "🇨🇭", "name": "Switzerland"},
    "sy": {"flag": "🇸🇾", "name": "Syrian Arab Republic"},
    "tw": {"flag": "🇹🇼", "name": "Taiwan, Province of China"},
    "tj": {"flag": "🇹🇯", "name": "Tajikistan"},
    "tz": {"flag": "🇹🇿", "name": "Tanzania, United Republic of"},
    "th": {"flag": "🇹🇭", "name": "Thailand"},
    "tl": {"flag": "🇹🇱", "name": "Timor-Leste"},
    "tg": {"flag": "🇹🇬", "name": "Togo"},
    "tk": {"flag": "🇹🇰", "name": "Tokelau"},
    "to": {"flag": "🇹🇴", "name": "Tonga"},
    "tt": {"flag": "🇹🇹", "name": "Trinidad and Tobago"},
    "tn": {"flag": "🇹🇳", "name": "Tunisia"},
    "tr": {"flag": "🇹🇷", "name": "Turkey"},
    "tm": {"flag": "🇹🇲", "name": "Turkmenistan"},
    "tc": {"flag": "🇹🇨", "name": "Turks and Caicos Islands"},
    "tv": {"flag": "🇹🇻", "name": "Tuvalu"},
    "ug": {"flag": "🇺🇬", "name": "Uganda"},
    "ua": {"flag": "🇺🇦", "name": "Ukraine"},
    "ae": {"flag": "🇦🇪", "name": "United Arab Emirates"},
    "gb": {"flag": "🇬🇧", "name": "United Kingdom"},
    "us": {"flag": "🇺🇸", "name": "United States"},
    "um": {"flag": "🇺🇲", "name": "United States Minor Outlying Islands"},
    "uy": {"flag": "🇺🇾", "name": "Uruguay"},
    "uz": {"flag": "🇺🇿", "name": "Uzbekistan"},
    "vu": {"flag": "🇻🇺", "name": "Vanuatu"},
    "ve": {"flag": "🇻🇪", "name": "Venezuela"},
    "vn": {"flag": "🇻🇳", "name": "Vietnam"},
    "vg": {"flag": "🇻🇬", "name": "Virgin Islands (British)"},
    "vi": {"flag": "🇻🇮", "name": "Virgin Islands (U.S.)"},
    "wf": {"flag": "🇼🇫", "name": "Wallis and Futuna"},
    "eh": {"flag": "🇪🇭", "name": "Western Sahara"},
    "ye": {"flag": "🇾🇪", "name": "Yemen"},
    "zm": {"flag": "🇿🇲", "name": "Zambia"},
    "zw": {"flag": "🇿🇼", "name": "Zimbabwe"},
}

# "🇮🇳 India" -> "in", for turning a displayed country back into a query value.
_DISPLAY_TO_CODE = {f"{v['flag']} {v['name']}": code for code, v in COUNTRY_MAP.items()}


def get_country_display(code: str) -> str:
    """
    Convert country code to display string with flag emoji and full name.

    Args:
        code: Two-letter country code (e.g., 'in', 'us', 'gb')

    Returns:
        Formatted string with flag emoji and country name (e.g., '🇮🇳 India')
    """
    normalized = code.lower()
    country_info = COUNTRY_MAP.get(normalized)

    if country_info:
        return f"{country_info['flag']} {country_info['name']}"
    else:
        # Fallback for unrecognized codes
        return f"🌐 {code.upper()}"


def get_country_code(display: str) -> str:
    """Invert get_country_display: '🇮🇳 India' -> 'in', '🌐 XK' -> 'xk'."""
    if display in _DISPLAY_TO_CODE:
        return _DISPLAY_TO_CODE[display]
    return display.removeprefix("🌐 ").strip().lower()
